name: Socials API Health Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check Socials API Health
        run: |
          urls=(
            "https://sniplinkapp.onrender.com"
            "https://portfolio-server-latest.onrender.com/socials"
            "https://user-auth-imui.onrender.com"
            "https://realchatapplicaton.onrender.com"
            "https://careerhub-app.onrender.com"
            "https://auth-project-web-latest.onrender.com"
          )

          for url in "${urls[@]}"; do
            response=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            if [ "$response" -eq 200 ]; then
              echo "$url is up and running!"
            else
              echo "⚠️ $url returned status code $response"
              exit 1  # Fail workflow if any API is down
            fi
          done
